# Generated by Django 6.0.1 on 2026-01-11 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('year_of_birth', models.CharField(max_length=10)),
                ('biography', models.TextField(blank=True)),
                ('country', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='BookType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_type', models.CharField(choices=[('glossy', 'глянцевая'), ('hardcover books', 'твердый переплет'), ('softcover books', 'мягкий переплет')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('the class', 'классика'), ('drama', 'драма'), ('comedi', 'комедия'), ('fantastic', 'фантастика')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.author')),
                ('book_type', models.ManyToManyField(blank=True, to='books.booktype')),
                ('genre', models.ManyToManyField(blank=True, to='books.genre')),
            ],
        ),
    ]
