# Generated by Django 6.0.1 on 2026-01-11 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('available', 'доступна'), ('issued', 'выдана'), ('repaired', 'ремонт')], max_length=20)),
                ('quantity', models.CharField(max_length=5)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
        ),
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.CharField(choices=[('Three days', 'три дня'), ('seven days', 'семь дней')], max_length=20)),
                ('date_of_issue', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField(auto_now=True)),
                ('forfeit', models.PositiveIntegerField()),
                ('book_copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrowing.bookcopy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
